<?php
/**
 * YopQrCodeInfoDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 线下业务
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Offline\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * YopQrCodeInfoDTO Class Doc Comment
 *
 * @category Class
 * @description 请修改我
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class YopQrCodeInfoDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'YopQrCodeInfoDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'qrCodeNo' => 'string',
        'createTime' => '\DateTime',
        'qrCodeName' => 'string',
        'qrCodeCfgs' => '\Yeepay\Yop\Sdk\Service\Offline\Model\QrCodeCfgInfo[]',
        'shopName' => 'string',
        'updateTime' => '\DateTime',
        'bindDevices' => '\Yeepay\Yop\Sdk\Service\Offline\Model\BindDevice[]',
        'parentMerchantNo' => 'string',
        'bindTerminalStatus' => 'string',
        'shopNo' => 'string',
        'status' => 'string',
        'merchantNo' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'qrCodeNo' => null,
        'createTime' => 'date-time',
        'qrCodeName' => null,
        'qrCodeCfgs' => null,
        'shopName' => null,
        'updateTime' => 'date-time',
        'bindDevices' => null,
        'parentMerchantNo' => null,
        'bindTerminalStatus' => null,
        'shopNo' => null,
        'status' => null,
        'merchantNo' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'qrCodeNo' => 'qrCodeNo',
        'createTime' => 'createTime',
        'qrCodeName' => 'qrCodeName',
        'qrCodeCfgs' => 'qrCodeCfgs',
        'shopName' => 'shopName',
        'updateTime' => 'updateTime',
        'bindDevices' => 'bindDevices',
        'parentMerchantNo' => 'parentMerchantNo',
        'bindTerminalStatus' => 'bindTerminalStatus',
        'shopNo' => 'shopNo',
        'status' => 'status',
        'merchantNo' => 'merchantNo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'qrCodeNo' => 'setQrCodeNo',
        'createTime' => 'setCreateTime',
        'qrCodeName' => 'setQrCodeName',
        'qrCodeCfgs' => 'setQrCodeCfgs',
        'shopName' => 'setShopName',
        'updateTime' => 'setUpdateTime',
        'bindDevices' => 'setBindDevices',
        'parentMerchantNo' => 'setParentMerchantNo',
        'bindTerminalStatus' => 'setBindTerminalStatus',
        'shopNo' => 'setShopNo',
        'status' => 'setStatus',
        'merchantNo' => 'setMerchantNo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'qrCodeNo' => 'getQrCodeNo',
        'createTime' => 'getCreateTime',
        'qrCodeName' => 'getQrCodeName',
        'qrCodeCfgs' => 'getQrCodeCfgs',
        'shopName' => 'getShopName',
        'updateTime' => 'getUpdateTime',
        'bindDevices' => 'getBindDevices',
        'parentMerchantNo' => 'getParentMerchantNo',
        'bindTerminalStatus' => 'getBindTerminalStatus',
        'shopNo' => 'getShopNo',
        'status' => 'getStatus',
        'merchantNo' => 'getMerchantNo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['qrCodeNo'] = isset($data['qrCodeNo']) ? $data['qrCodeNo'] : null;
        $this->container['createTime'] = isset($data['createTime']) ? $data['createTime'] : null;
        $this->container['qrCodeName'] = isset($data['qrCodeName']) ? $data['qrCodeName'] : null;
        $this->container['qrCodeCfgs'] = isset($data['qrCodeCfgs']) ? $data['qrCodeCfgs'] : null;
        $this->container['shopName'] = isset($data['shopName']) ? $data['shopName'] : null;
        $this->container['updateTime'] = isset($data['updateTime']) ? $data['updateTime'] : null;
        $this->container['bindDevices'] = isset($data['bindDevices']) ? $data['bindDevices'] : null;
        $this->container['parentMerchantNo'] = isset($data['parentMerchantNo']) ? $data['parentMerchantNo'] : null;
        $this->container['bindTerminalStatus'] = isset($data['bindTerminalStatus']) ? $data['bindTerminalStatus'] : null;
        $this->container['shopNo'] = isset($data['shopNo']) ? $data['shopNo'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['merchantNo'] = isset($data['merchantNo']) ? $data['merchantNo'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets qrCodeNo
     *
     * @return string
     */
    public function getQrCodeNo()
    {
        return $this->container['qrCodeNo'];
    }

    /**
     * Sets qrCodeNo
     *
     * @param string $qrCodeNo <pre>台牌号</pre>
     *
     * @return $this
     */
    public function setQrCodeNo($qrCodeNo)
    {
        $this->container['qrCodeNo'] = $qrCodeNo;

        return $this;
    }

    /**
     * Gets createTime
     *
     * @return \DateTime
     */
    public function getCreateTime()
    {
        return $this->container['createTime'];
    }

    /**
     * Sets createTime
     *
     * @param \DateTime $createTime <pre>生成时间</pre>
     *
     * @return $this
     */
    public function setCreateTime($createTime)
    {
        $this->container['createTime'] = $createTime;

        return $this;
    }

    /**
     * Gets qrCodeName
     *
     * @return string
     */
    public function getQrCodeName()
    {
        return $this->container['qrCodeName'];
    }

    /**
     * Sets qrCodeName
     *
     * @param string $qrCodeName <pre>台牌名称</pre>
     *
     * @return $this
     */
    public function setQrCodeName($qrCodeName)
    {
        $this->container['qrCodeName'] = $qrCodeName;

        return $this;
    }

    /**
     * Gets qrCodeCfgs
     *
     * @return \Yeepay\Yop\Sdk\Service\Offline\Model\QrCodeCfgInfo[]
     */
    public function getQrCodeCfgs()
    {
        return $this->container['qrCodeCfgs'];
    }

    /**
     * Sets qrCodeCfgs
     *
     * @param \Yeepay\Yop\Sdk\Service\Offline\Model\QrCodeCfgInfo[] $qrCodeCfgs <pre>台牌备注</pre>
     *
     * @return $this
     */
    public function setQrCodeCfgs($qrCodeCfgs)
    {
        $this->container['qrCodeCfgs'] = $qrCodeCfgs;

        return $this;
    }

    /**
     * Gets shopName
     *
     * @return string
     */
    public function getShopName()
    {
        return $this->container['shopName'];
    }

    /**
     * Sets shopName
     *
     * @param string $shopName <pre>网点名称</pre>
     *
     * @return $this
     */
    public function setShopName($shopName)
    {
        $this->container['shopName'] = $shopName;

        return $this;
    }

    /**
     * Gets updateTime
     *
     * @return \DateTime
     */
    public function getUpdateTime()
    {
        return $this->container['updateTime'];
    }

    /**
     * Sets updateTime
     *
     * @param \DateTime $updateTime <pre>最近更新时间</pre>
     *
     * @return $this
     */
    public function setUpdateTime($updateTime)
    {
        $this->container['updateTime'] = $updateTime;

        return $this;
    }

    /**
     * Gets bindDevices
     *
     * @return \Yeepay\Yop\Sdk\Service\Offline\Model\BindDevice[]
     */
    public function getBindDevices()
    {
        return $this->container['bindDevices'];
    }

    /**
     * Sets bindDevices
     *
     * @param \Yeepay\Yop\Sdk\Service\Offline\Model\BindDevice[] $bindDevices <pre>台牌播报设备</pre>
     *
     * @return $this
     */
    public function setBindDevices($bindDevices)
    {
        $this->container['bindDevices'] = $bindDevices;

        return $this;
    }

    /**
     * Gets parentMerchantNo
     *
     * @return string
     */
    public function getParentMerchantNo()
    {
        return $this->container['parentMerchantNo'];
    }

    /**
     * Sets parentMerchantNo
     *
     * @param string $parentMerchantNo <pre>采购商编</pre>
     *
     * @return $this
     */
    public function setParentMerchantNo($parentMerchantNo)
    {
        $this->container['parentMerchantNo'] = $parentMerchantNo;

        return $this;
    }

    /**
     * Gets bindTerminalStatus
     *
     * @return string
     */
    public function getBindTerminalStatus()
    {
        return $this->container['bindTerminalStatus'];
    }

    /**
     * Sets bindTerminalStatus
     *
     * @param string $bindTerminalStatus <pre>绑定播报设备状态</pre>
     *
     * @return $this
     */
    public function setBindTerminalStatus($bindTerminalStatus)
    {
        $this->container['bindTerminalStatus'] = $bindTerminalStatus;

        return $this;
    }

    /**
     * Gets shopNo
     *
     * @return string
     */
    public function getShopNo()
    {
        return $this->container['shopNo'];
    }

    /**
     * Sets shopNo
     *
     * @param string $shopNo <pre>网点编号</pre>
     *
     * @return $this
     */
    public function setShopNo($shopNo)
    {
        $this->container['shopNo'] = $shopNo;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status <pre>状态</pre>
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets merchantNo
     *
     * @return string
     */
    public function getMerchantNo()
    {
        return $this->container['merchantNo'];
    }

    /**
     * Sets merchantNo
     *
     * @param string $merchantNo <pre>商编</pre>
     *
     * @return $this
     */
    public function setMerchantNo($merchantNo)
    {
        $this->container['merchantNo'] = $merchantNo;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


