<?php
/**
 * YopUpdateQrCodeCfgReqDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 线下业务
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Offline\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * YopUpdateQrCodeCfgReqDTO Class Doc Comment
 *
 * @category Class
 * @description 请修改我
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class YopUpdateQrCodeCfgReqDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'YopUpdateQrCodeCfgReqDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'qrCodeNo' => 'string',
        'qrCodeName' => 'string',
        'qrCodeCfgs' => '\Yeepay\Yop\Sdk\Service\Offline\Model\QrCodeCfgInfo[]',
        'parentMerchantNo' => 'string',
        'merchantNo' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'qrCodeNo' => null,
        'qrCodeName' => null,
        'qrCodeCfgs' => null,
        'parentMerchantNo' => null,
        'merchantNo' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'qrCodeNo' => 'qrCodeNo',
        'qrCodeName' => 'qrCodeName',
        'qrCodeCfgs' => 'qrCodeCfgs',
        'parentMerchantNo' => 'parentMerchantNo',
        'merchantNo' => 'merchantNo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'qrCodeNo' => 'setQrCodeNo',
        'qrCodeName' => 'setQrCodeName',
        'qrCodeCfgs' => 'setQrCodeCfgs',
        'parentMerchantNo' => 'setParentMerchantNo',
        'merchantNo' => 'setMerchantNo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'qrCodeNo' => 'getQrCodeNo',
        'qrCodeName' => 'getQrCodeName',
        'qrCodeCfgs' => 'getQrCodeCfgs',
        'parentMerchantNo' => 'getParentMerchantNo',
        'merchantNo' => 'getMerchantNo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['qrCodeNo'] = isset($data['qrCodeNo']) ? $data['qrCodeNo'] : null;
        $this->container['qrCodeName'] = isset($data['qrCodeName']) ? $data['qrCodeName'] : null;
        $this->container['qrCodeCfgs'] = isset($data['qrCodeCfgs']) ? $data['qrCodeCfgs'] : null;
        $this->container['parentMerchantNo'] = isset($data['parentMerchantNo']) ? $data['parentMerchantNo'] : null;
        $this->container['merchantNo'] = isset($data['merchantNo']) ? $data['merchantNo'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['qrCodeNo'] === null) {
            $invalidProperties[] = "'qrCodeNo' can't be null";
        }
        if ($this->container['qrCodeName'] === null) {
            $invalidProperties[] = "'qrCodeName' can't be null";
        }
        if ($this->container['parentMerchantNo'] === null) {
            $invalidProperties[] = "'parentMerchantNo' can't be null";
        }
        if ($this->container['merchantNo'] === null) {
            $invalidProperties[] = "'merchantNo' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets qrCodeNo
     *
     * @return string
     */
    public function getQrCodeNo()
    {
        return $this->container['qrCodeNo'];
    }

    /**
     * Sets qrCodeNo
     *
     * @param string $qrCodeNo <pre>台牌序列号</pre>
     *
     * @return $this
     */
    public function setQrCodeNo($qrCodeNo)
    {
        $this->container['qrCodeNo'] = $qrCodeNo;

        return $this;
    }

    /**
     * Gets qrCodeName
     *
     * @return string
     */
    public function getQrCodeName()
    {
        return $this->container['qrCodeName'];
    }

    /**
     * Sets qrCodeName
     *
     * @param string $qrCodeName <pre>台牌名称</pre>
     *
     * @return $this
     */
    public function setQrCodeName($qrCodeName)
    {
        $this->container['qrCodeName'] = $qrCodeName;

        return $this;
    }

    /**
     * Gets qrCodeCfgs
     *
     * @return \Yeepay\Yop\Sdk\Service\Offline\Model\QrCodeCfgInfo[]
     */
    public function getQrCodeCfgs()
    {
        return $this->container['qrCodeCfgs'];
    }

    /**
     * Sets qrCodeCfgs
     *
     * @param \Yeepay\Yop\Sdk\Service\Offline\Model\QrCodeCfgInfo[] $qrCodeCfgs <pre>台牌备注，不超过10个</pre>
     *
     * @return $this
     */
    public function setQrCodeCfgs($qrCodeCfgs)
    {
        $this->container['qrCodeCfgs'] = $qrCodeCfgs;

        return $this;
    }

    /**
     * Gets parentMerchantNo
     *
     * @return string
     */
    public function getParentMerchantNo()
    {
        return $this->container['parentMerchantNo'];
    }

    /**
     * Sets parentMerchantNo
     *
     * @param string $parentMerchantNo <div><span class=\"text-only\">采购商编，记录在易宝生成台牌的商编，该商编对台牌有管理权限</span></div>
     *
     * @return $this
     */
    public function setParentMerchantNo($parentMerchantNo)
    {
        $this->container['parentMerchantNo'] = $parentMerchantNo;

        return $this;
    }

    /**
     * Gets merchantNo
     *
     * @return string
     */
    public function getMerchantNo()
    {
        return $this->container['merchantNo'];
    }

    /**
     * Sets merchantNo
     *
     * @param string $merchantNo <div><span class=\"text-only\">绑定台牌真实收款的商编，该商编对台牌有使用权限</span></div>
     *
     * @return $this
     */
    public function setMerchantNo($merchantNo)
    {
        $this->container['merchantNo'] = $merchantNo;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


