<?php
/**
 * WechatComplaintInfoFlatResponseDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 聚合支付
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Aggpay\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * WechatComplaintInfoFlatResponseDTO Class Doc Comment
 *
 * @category Class
 * @description 返回信息
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WechatComplaintInfoFlatResponseDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'WechatComplaintInfoFlatResponseDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'code' => 'string',
        'complaintTime' => 'string',
        'complaintContact' => 'string',
        'complaintState' => 'string',
        'complaintDetail' => 'string',
        'wechatMerchantNo' => 'string',
        'returnId' => 'string',
        'waybillId' => 'string',
        'complaintNo' => 'string',
        'amount' => 'string',
        'appealState' => 'string',
        'isResponse' => 'bool',
        'complaintMediaDTOList' => 'string',
        'wechatOrderNo' => 'string',
        'complaintCount' => 'int',
        'message' => 'string',
        'deliveryOrderStatus' => 'string',
        'merchantOrderNo' => 'string',
        'tradeTime' => 'string',
        'complaintOpenId' => 'string',
        'bankOrderNo' => 'string',
        'deliveryName' => 'string',
        'merchantNo' => 'string',
        'isFullRefunded' => 'bool',
        'complaintExpireTime' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'code' => null,
        'complaintTime' => null,
        'complaintContact' => null,
        'complaintState' => null,
        'complaintDetail' => null,
        'wechatMerchantNo' => null,
        'returnId' => null,
        'waybillId' => null,
        'complaintNo' => null,
        'amount' => null,
        'appealState' => null,
        'isResponse' => null,
        'complaintMediaDTOList' => null,
        'wechatOrderNo' => null,
        'complaintCount' => 'int32',
        'message' => null,
        'deliveryOrderStatus' => null,
        'merchantOrderNo' => null,
        'tradeTime' => null,
        'complaintOpenId' => null,
        'bankOrderNo' => null,
        'deliveryName' => null,
        'merchantNo' => null,
        'isFullRefunded' => null,
        'complaintExpireTime' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'code' => 'code',
        'complaintTime' => 'complaintTime',
        'complaintContact' => 'complaintContact',
        'complaintState' => 'complaintState',
        'complaintDetail' => 'complaintDetail',
        'wechatMerchantNo' => 'wechatMerchantNo',
        'returnId' => 'returnId',
        'waybillId' => 'waybillId',
        'complaintNo' => 'complaintNo',
        'amount' => 'amount',
        'appealState' => 'appealState',
        'isResponse' => 'isResponse',
        'complaintMediaDTOList' => 'complaintMediaDTOList',
        'wechatOrderNo' => 'wechatOrderNo',
        'complaintCount' => 'complaintCount',
        'message' => 'message',
        'deliveryOrderStatus' => 'deliveryOrderStatus',
        'merchantOrderNo' => 'merchantOrderNo',
        'tradeTime' => 'tradeTime',
        'complaintOpenId' => 'complaintOpenId',
        'bankOrderNo' => 'bankOrderNo',
        'deliveryName' => 'deliveryName',
        'merchantNo' => 'merchantNo',
        'isFullRefunded' => 'isFullRefunded',
        'complaintExpireTime' => 'complaintExpireTime'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'code' => 'setCode',
        'complaintTime' => 'setComplaintTime',
        'complaintContact' => 'setComplaintContact',
        'complaintState' => 'setComplaintState',
        'complaintDetail' => 'setComplaintDetail',
        'wechatMerchantNo' => 'setWechatMerchantNo',
        'returnId' => 'setReturnId',
        'waybillId' => 'setWaybillId',
        'complaintNo' => 'setComplaintNo',
        'amount' => 'setAmount',
        'appealState' => 'setAppealState',
        'isResponse' => 'setIsResponse',
        'complaintMediaDTOList' => 'setComplaintMediaDTOList',
        'wechatOrderNo' => 'setWechatOrderNo',
        'complaintCount' => 'setComplaintCount',
        'message' => 'setMessage',
        'deliveryOrderStatus' => 'setDeliveryOrderStatus',
        'merchantOrderNo' => 'setMerchantOrderNo',
        'tradeTime' => 'setTradeTime',
        'complaintOpenId' => 'setComplaintOpenId',
        'bankOrderNo' => 'setBankOrderNo',
        'deliveryName' => 'setDeliveryName',
        'merchantNo' => 'setMerchantNo',
        'isFullRefunded' => 'setIsFullRefunded',
        'complaintExpireTime' => 'setComplaintExpireTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'code' => 'getCode',
        'complaintTime' => 'getComplaintTime',
        'complaintContact' => 'getComplaintContact',
        'complaintState' => 'getComplaintState',
        'complaintDetail' => 'getComplaintDetail',
        'wechatMerchantNo' => 'getWechatMerchantNo',
        'returnId' => 'getReturnId',
        'waybillId' => 'getWaybillId',
        'complaintNo' => 'getComplaintNo',
        'amount' => 'getAmount',
        'appealState' => 'getAppealState',
        'isResponse' => 'getIsResponse',
        'complaintMediaDTOList' => 'getComplaintMediaDTOList',
        'wechatOrderNo' => 'getWechatOrderNo',
        'complaintCount' => 'getComplaintCount',
        'message' => 'getMessage',
        'deliveryOrderStatus' => 'getDeliveryOrderStatus',
        'merchantOrderNo' => 'getMerchantOrderNo',
        'tradeTime' => 'getTradeTime',
        'complaintOpenId' => 'getComplaintOpenId',
        'bankOrderNo' => 'getBankOrderNo',
        'deliveryName' => 'getDeliveryName',
        'merchantNo' => 'getMerchantNo',
        'isFullRefunded' => 'getIsFullRefunded',
        'complaintExpireTime' => 'getComplaintExpireTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['code'] = isset($data['code']) ? $data['code'] : null;
        $this->container['complaintTime'] = isset($data['complaintTime']) ? $data['complaintTime'] : null;
        $this->container['complaintContact'] = isset($data['complaintContact']) ? $data['complaintContact'] : null;
        $this->container['complaintState'] = isset($data['complaintState']) ? $data['complaintState'] : null;
        $this->container['complaintDetail'] = isset($data['complaintDetail']) ? $data['complaintDetail'] : null;
        $this->container['wechatMerchantNo'] = isset($data['wechatMerchantNo']) ? $data['wechatMerchantNo'] : null;
        $this->container['returnId'] = isset($data['returnId']) ? $data['returnId'] : null;
        $this->container['waybillId'] = isset($data['waybillId']) ? $data['waybillId'] : null;
        $this->container['complaintNo'] = isset($data['complaintNo']) ? $data['complaintNo'] : null;
        $this->container['amount'] = isset($data['amount']) ? $data['amount'] : null;
        $this->container['appealState'] = isset($data['appealState']) ? $data['appealState'] : null;
        $this->container['isResponse'] = isset($data['isResponse']) ? $data['isResponse'] : null;
        $this->container['complaintMediaDTOList'] = isset($data['complaintMediaDTOList']) ? $data['complaintMediaDTOList'] : null;
        $this->container['wechatOrderNo'] = isset($data['wechatOrderNo']) ? $data['wechatOrderNo'] : null;
        $this->container['complaintCount'] = isset($data['complaintCount']) ? $data['complaintCount'] : null;
        $this->container['message'] = isset($data['message']) ? $data['message'] : null;
        $this->container['deliveryOrderStatus'] = isset($data['deliveryOrderStatus']) ? $data['deliveryOrderStatus'] : null;
        $this->container['merchantOrderNo'] = isset($data['merchantOrderNo']) ? $data['merchantOrderNo'] : null;
        $this->container['tradeTime'] = isset($data['tradeTime']) ? $data['tradeTime'] : null;
        $this->container['complaintOpenId'] = isset($data['complaintOpenId']) ? $data['complaintOpenId'] : null;
        $this->container['bankOrderNo'] = isset($data['bankOrderNo']) ? $data['bankOrderNo'] : null;
        $this->container['deliveryName'] = isset($data['deliveryName']) ? $data['deliveryName'] : null;
        $this->container['merchantNo'] = isset($data['merchantNo']) ? $data['merchantNo'] : null;
        $this->container['isFullRefunded'] = isset($data['isFullRefunded']) ? $data['isFullRefunded'] : null;
        $this->container['complaintExpireTime'] = isset($data['complaintExpireTime']) ? $data['complaintExpireTime'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['code'] === null) {
            $invalidProperties[] = "'code' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code <p>返回码 00000：成功<br />非00000：失败</p>
     *
     * @return $this
     */
    public function setCode($code)
    {
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets complaintTime
     *
     * @return string
     */
    public function getComplaintTime()
    {
        return $this->container['complaintTime'];
    }

    /**
     * Sets complaintTime
     *
     * @param string $complaintTime <p>消费者投诉时间，格式为yyyy-MM-dd HH:mm:ss，<br />yyyy-MM-dd表示年月日，HH:mm:ss表示时分秒。</p>
     *
     * @return $this
     */
    public function setComplaintTime($complaintTime)
    {
        $this->container['complaintTime'] = $complaintTime;

        return $this;
    }

    /**
     * Gets complaintContact
     *
     * @return string
     */
    public function getComplaintContact()
    {
        return $this->container['complaintContact'];
    }

    /**
     * Sets complaintContact
     *
     * @param string $complaintContact <p>投诉人联系方式</p>
     *
     * @return $this
     */
    public function setComplaintContact($complaintContact)
    {
        $this->container['complaintContact'] = $complaintContact;

        return $this;
    }

    /**
     * Gets complaintState
     *
     * @return string
     */
    public function getComplaintState()
    {
        return $this->container['complaintState'];
    }

    /**
     * Sets complaintState
     *
     * @param string $complaintState <p>投诉单状态</p>
     *
     * @return $this
     */
    public function setComplaintState($complaintState)
    {
        $this->container['complaintState'] = $complaintState;

        return $this;
    }

    /**
     * Gets complaintDetail
     *
     * @return string
     */
    public function getComplaintDetail()
    {
        return $this->container['complaintDetail'];
    }

    /**
     * Sets complaintDetail
     *
     * @param string $complaintDetail <p>投诉的具体描述</p>
     *
     * @return $this
     */
    public function setComplaintDetail($complaintDetail)
    {
        $this->container['complaintDetail'] = $complaintDetail;

        return $this;
    }

    /**
     * Gets wechatMerchantNo
     *
     * @return string
     */
    public function getWechatMerchantNo()
    {
        return $this->container['wechatMerchantNo'];
    }

    /**
     * Sets wechatMerchantNo
     *
     * @param string $wechatMerchantNo <div data-zone-id=\"0\" data-line-index=\"0\" data-line=\"true\">被诉的微信商户号示</div>
     *
     * @return $this
     */
    public function setWechatMerchantNo($wechatMerchantNo)
    {
        $this->container['wechatMerchantNo'] = $wechatMerchantNo;

        return $this;
    }

    /**
     * Gets returnId
     *
     * @return string
     */
    public function getReturnId()
    {
        return $this->container['returnId'];
    }

    /**
     * Sets returnId
     *
     * @param string $returnId <p>投诉单对应的退货 id</p>
     *
     * @return $this
     */
    public function setReturnId($returnId)
    {
        $this->container['returnId'] = $returnId;

        return $this;
    }

    /**
     * Gets waybillId
     *
     * @return string
     */
    public function getWaybillId()
    {
        return $this->container['waybillId'];
    }

    /**
     * Sets waybillId
     *
     * @param string $waybillId <p>运单号</p>
     *
     * @return $this
     */
    public function setWaybillId($waybillId)
    {
        $this->container['waybillId'] = $waybillId;

        return $this;
    }

    /**
     * Gets complaintNo
     *
     * @return string
     */
    public function getComplaintNo()
    {
        return $this->container['complaintNo'];
    }

    /**
     * Sets complaintNo
     *
     * @param string $complaintNo <p>投诉单号</p>
     *
     * @return $this
     */
    public function setComplaintNo($complaintNo)
    {
        $this->container['complaintNo'] = $complaintNo;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return string
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param string $amount <p>订单金额</p>
     *
     * @return $this
     */
    public function setAmount($amount)
    {
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets appealState
     *
     * @return string
     */
    public function getAppealState()
    {
        return $this->container['appealState'];
    }

    /**
     * Sets appealState
     *
     * @param string $appealState <p>申诉状态</p>
     *
     * @return $this
     */
    public function setAppealState($appealState)
    {
        $this->container['appealState'] = $appealState;

        return $this;
    }

    /**
     * Gets isResponse
     *
     * @return bool
     */
    public function getIsResponse()
    {
        return $this->container['isResponse'];
    }

    /**
     * Sets isResponse
     *
     * @param bool $isResponse <p>是否有待回复留言</p>
     *
     * @return $this
     */
    public function setIsResponse($isResponse)
    {
        $this->container['isResponse'] = $isResponse;

        return $this;
    }

    /**
     * Gets complaintMediaDTOList
     *
     * @return string
     */
    public function getComplaintMediaDTOList()
    {
        return $this->container['complaintMediaDTOList'];
    }

    /**
     * Sets complaintMediaDTOList
     *
     * @param string $complaintMediaDTOList <p>用户投诉相关资料</p>
     *
     * @return $this
     */
    public function setComplaintMediaDTOList($complaintMediaDTOList)
    {
        $this->container['complaintMediaDTOList'] = $complaintMediaDTOList;

        return $this;
    }

    /**
     * Gets wechatOrderNo
     *
     * @return string
     */
    public function getWechatOrderNo()
    {
        return $this->container['wechatOrderNo'];
    }

    /**
     * Sets wechatOrderNo
     *
     * @param string $wechatOrderNo <p>微信订单号</p>
     *
     * @return $this
     */
    public function setWechatOrderNo($wechatOrderNo)
    {
        $this->container['wechatOrderNo'] = $wechatOrderNo;

        return $this;
    }

    /**
     * Gets complaintCount
     *
     * @return int
     */
    public function getComplaintCount()
    {
        return $this->container['complaintCount'];
    }

    /**
     * Sets complaintCount
     *
     * @param int $complaintCount <p>用户投诉次数</p>
     *
     * @return $this
     */
    public function setComplaintCount($complaintCount)
    {
        $this->container['complaintCount'] = $complaintCount;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string $message <p>返回信息</p>
     *
     * @return $this
     */
    public function setMessage($message)
    {
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets deliveryOrderStatus
     *
     * @return string
     */
    public function getDeliveryOrderStatus()
    {
        return $this->container['deliveryOrderStatus'];
    }

    /**
     * Sets deliveryOrderStatus
     *
     * @param string $deliveryOrderStatus <p>运单状态</p>
     *
     * @return $this
     */
    public function setDeliveryOrderStatus($deliveryOrderStatus)
    {
        $this->container['deliveryOrderStatus'] = $deliveryOrderStatus;

        return $this;
    }

    /**
     * Gets merchantOrderNo
     *
     * @return string
     */
    public function getMerchantOrderNo()
    {
        return $this->container['merchantOrderNo'];
    }

    /**
     * Sets merchantOrderNo
     *
     * @param string $merchantOrderNo <p>商户订单号</p>
     *
     * @return $this
     */
    public function setMerchantOrderNo($merchantOrderNo)
    {
        $this->container['merchantOrderNo'] = $merchantOrderNo;

        return $this;
    }

    /**
     * Gets tradeTime
     *
     * @return string
     */
    public function getTradeTime()
    {
        return $this->container['tradeTime'];
    }

    /**
     * Sets tradeTime
     *
     * @param string $tradeTime <p>交易时间</p>
     *
     * @return $this
     */
    public function setTradeTime($tradeTime)
    {
        $this->container['tradeTime'] = $tradeTime;

        return $this;
    }

    /**
     * Gets complaintOpenId
     *
     * @return string
     */
    public function getComplaintOpenId()
    {
        return $this->container['complaintOpenId'];
    }

    /**
     * Sets complaintOpenId
     *
     * @param string $complaintOpenId <p>投诉人 openId</p>
     *
     * @return $this
     */
    public function setComplaintOpenId($complaintOpenId)
    {
        $this->container['complaintOpenId'] = $complaintOpenId;

        return $this;
    }

    /**
     * Gets bankOrderNo
     *
     * @return string
     */
    public function getBankOrderNo()
    {
        return $this->container['bankOrderNo'];
    }

    /**
     * Sets bankOrderNo
     *
     * @param string $bankOrderNo <p>银行订单号</p>
     *
     * @return $this
     */
    public function setBankOrderNo($bankOrderNo)
    {
        $this->container['bankOrderNo'] = $bankOrderNo;

        return $this;
    }

    /**
     * Gets deliveryName
     *
     * @return string
     */
    public function getDeliveryName()
    {
        return $this->container['deliveryName'];
    }

    /**
     * Sets deliveryName
     *
     * @param string $deliveryName <p>运力公司</p>
     *
     * @return $this
     */
    public function setDeliveryName($deliveryName)
    {
        $this->container['deliveryName'] = $deliveryName;

        return $this;
    }

    /**
     * Gets merchantNo
     *
     * @return string
     */
    public function getMerchantNo()
    {
        return $this->container['merchantNo'];
    }

    /**
     * Sets merchantNo
     *
     * @param string $merchantNo <p>商户编号</p>
     *
     * @return $this
     */
    public function setMerchantNo($merchantNo)
    {
        $this->container['merchantNo'] = $merchantNo;

        return $this;
    }

    /**
     * Gets isFullRefunded
     *
     * @return bool
     */
    public function getIsFullRefunded()
    {
        return $this->container['isFullRefunded'];
    }

    /**
     * Sets isFullRefunded
     *
     * @param bool $isFullRefunded <p>是否已全额退款</p>
     *
     * @return $this
     */
    public function setIsFullRefunded($isFullRefunded)
    {
        $this->container['isFullRefunded'] = $isFullRefunded;

        return $this;
    }

    /**
     * Gets complaintExpireTime
     *
     * @return string
     */
    public function getComplaintExpireTime()
    {
        return $this->container['complaintExpireTime'];
    }

    /**
     * Sets complaintExpireTime
     *
     * @param string $complaintExpireTime <p>投诉当前状态到期时间</p>
     *
     * @return $this
     */
    public function setComplaintExpireTime($complaintExpireTime)
    {
        $this->container['complaintExpireTime'] = $complaintExpireTime;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


