<?php
/**
 * RefundOrderResponseDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 旅游资源
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\TravelResources\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * RefundOrderResponseDTO Class Doc Comment
 *
 * @category Class
 * @description 退款订单返回参数
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RefundOrderResponseDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RefundOrderResponseDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'code' => 'string',
        'message' => 'string',
        'parentMerchantNo' => 'string',
        'parentMerchantRequestNo' => 'string',
        'parentMerchantRefundRequestNo' => 'string',
        'merchantNo' => 'string',
        'merchantRequestNo' => 'string',
        'merchantRefundRequestNo' => 'string',
        'purchasePlatformId' => 'string',
        'systemOrderNo' => 'string',
        'refundAmount' => 'float',
        'status' => 'string',
        'refundSuccessTime' => 'string',
        'trxType' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'code' => null,
        'message' => null,
        'parentMerchantNo' => null,
        'parentMerchantRequestNo' => null,
        'parentMerchantRefundRequestNo' => null,
        'merchantNo' => null,
        'merchantRequestNo' => null,
        'merchantRefundRequestNo' => null,
        'purchasePlatformId' => null,
        'systemOrderNo' => null,
        'refundAmount' => null,
        'status' => null,
        'refundSuccessTime' => null,
        'trxType' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'code' => 'code',
        'message' => 'message',
        'parentMerchantNo' => 'parentMerchantNo',
        'parentMerchantRequestNo' => 'parentMerchantRequestNo',
        'parentMerchantRefundRequestNo' => 'parentMerchantRefundRequestNo',
        'merchantNo' => 'merchantNo',
        'merchantRequestNo' => 'merchantRequestNo',
        'merchantRefundRequestNo' => 'merchantRefundRequestNo',
        'purchasePlatformId' => 'purchasePlatformId',
        'systemOrderNo' => 'systemOrderNo',
        'refundAmount' => 'refundAmount',
        'status' => 'status',
        'refundSuccessTime' => 'refundSuccessTime',
        'trxType' => 'trxType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'code' => 'setCode',
        'message' => 'setMessage',
        'parentMerchantNo' => 'setParentMerchantNo',
        'parentMerchantRequestNo' => 'setParentMerchantRequestNo',
        'parentMerchantRefundRequestNo' => 'setParentMerchantRefundRequestNo',
        'merchantNo' => 'setMerchantNo',
        'merchantRequestNo' => 'setMerchantRequestNo',
        'merchantRefundRequestNo' => 'setMerchantRefundRequestNo',
        'purchasePlatformId' => 'setPurchasePlatformId',
        'systemOrderNo' => 'setSystemOrderNo',
        'refundAmount' => 'setRefundAmount',
        'status' => 'setStatus',
        'refundSuccessTime' => 'setRefundSuccessTime',
        'trxType' => 'setTrxType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'code' => 'getCode',
        'message' => 'getMessage',
        'parentMerchantNo' => 'getParentMerchantNo',
        'parentMerchantRequestNo' => 'getParentMerchantRequestNo',
        'parentMerchantRefundRequestNo' => 'getParentMerchantRefundRequestNo',
        'merchantNo' => 'getMerchantNo',
        'merchantRequestNo' => 'getMerchantRequestNo',
        'merchantRefundRequestNo' => 'getMerchantRefundRequestNo',
        'purchasePlatformId' => 'getPurchasePlatformId',
        'systemOrderNo' => 'getSystemOrderNo',
        'refundAmount' => 'getRefundAmount',
        'status' => 'getStatus',
        'refundSuccessTime' => 'getRefundSuccessTime',
        'trxType' => 'getTrxType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['code'] = isset($data['code']) ? $data['code'] : null;
        $this->container['message'] = isset($data['message']) ? $data['message'] : null;
        $this->container['parentMerchantNo'] = isset($data['parentMerchantNo']) ? $data['parentMerchantNo'] : null;
        $this->container['parentMerchantRequestNo'] = isset($data['parentMerchantRequestNo']) ? $data['parentMerchantRequestNo'] : null;
        $this->container['parentMerchantRefundRequestNo'] = isset($data['parentMerchantRefundRequestNo']) ? $data['parentMerchantRefundRequestNo'] : null;
        $this->container['merchantNo'] = isset($data['merchantNo']) ? $data['merchantNo'] : null;
        $this->container['merchantRequestNo'] = isset($data['merchantRequestNo']) ? $data['merchantRequestNo'] : null;
        $this->container['merchantRefundRequestNo'] = isset($data['merchantRefundRequestNo']) ? $data['merchantRefundRequestNo'] : null;
        $this->container['purchasePlatformId'] = isset($data['purchasePlatformId']) ? $data['purchasePlatformId'] : null;
        $this->container['systemOrderNo'] = isset($data['systemOrderNo']) ? $data['systemOrderNo'] : null;
        $this->container['refundAmount'] = isset($data['refundAmount']) ? $data['refundAmount'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['refundSuccessTime'] = isset($data['refundSuccessTime']) ? $data['refundSuccessTime'] : null;
        $this->container['trxType'] = isset($data['trxType']) ? $data['trxType'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['merchantNo'] === null) {
            $invalidProperties[] = "'merchantNo' can't be null";
        }
        if ($this->container['merchantRequestNo'] === null) {
            $invalidProperties[] = "'merchantRequestNo' can't be null";
        }
        if ($this->container['merchantRefundRequestNo'] === null) {
            $invalidProperties[] = "'merchantRefundRequestNo' can't be null";
        }
        if ($this->container['purchasePlatformId'] === null) {
            $invalidProperties[] = "'purchasePlatformId' can't be null";
        }
        if ($this->container['systemOrderNo'] === null) {
            $invalidProperties[] = "'systemOrderNo' can't be null";
        }
        if ($this->container['refundAmount'] === null) {
            $invalidProperties[] = "'refundAmount' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code <p>代表本次请求成功，订单状态需要关注status</p>
     *
     * @return $this
     */
    public function setCode($code)
    {
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string $message message
     *
     * @return $this
     */
    public function setMessage($message)
    {
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets parentMerchantNo
     *
     * @return string
     */
    public function getParentMerchantNo()
    {
        return $this->container['parentMerchantNo'];
    }

    /**
     * Sets parentMerchantNo
     *
     * @param string $parentMerchantNo <pre>请求方商编</pre>
     *
     * @return $this
     */
    public function setParentMerchantNo($parentMerchantNo)
    {
        $this->container['parentMerchantNo'] = $parentMerchantNo;

        return $this;
    }

    /**
     * Gets parentMerchantRequestNo
     *
     * @return string
     */
    public function getParentMerchantRequestNo()
    {
        return $this->container['parentMerchantRequestNo'];
    }

    /**
     * Sets parentMerchantRequestNo
     *
     * @param string $parentMerchantRequestNo <p>请求方订单号</p>
     *
     * @return $this
     */
    public function setParentMerchantRequestNo($parentMerchantRequestNo)
    {
        $this->container['parentMerchantRequestNo'] = $parentMerchantRequestNo;

        return $this;
    }

    /**
     * Gets parentMerchantRefundRequestNo
     *
     * @return string
     */
    public function getParentMerchantRefundRequestNo()
    {
        return $this->container['parentMerchantRefundRequestNo'];
    }

    /**
     * Sets parentMerchantRefundRequestNo
     *
     * @param string $parentMerchantRefundRequestNo <p>请求方退款订单号</p>
     *
     * @return $this
     */
    public function setParentMerchantRefundRequestNo($parentMerchantRefundRequestNo)
    {
        $this->container['parentMerchantRefundRequestNo'] = $parentMerchantRefundRequestNo;

        return $this;
    }

    /**
     * Gets merchantNo
     *
     * @return string
     */
    public function getMerchantNo()
    {
        return $this->container['merchantNo'];
    }

    /**
     * Sets merchantNo
     *
     * @param string $merchantNo <p>业务商编</p>
     *
     * @return $this
     */
    public function setMerchantNo($merchantNo)
    {
        $this->container['merchantNo'] = $merchantNo;

        return $this;
    }

    /**
     * Gets merchantRequestNo
     *
     * @return string
     */
    public function getMerchantRequestNo()
    {
        return $this->container['merchantRequestNo'];
    }

    /**
     * Sets merchantRequestNo
     *
     * @param string $merchantRequestNo <p>业务商户订单号</p>
     *
     * @return $this
     */
    public function setMerchantRequestNo($merchantRequestNo)
    {
        $this->container['merchantRequestNo'] = $merchantRequestNo;

        return $this;
    }

    /**
     * Gets merchantRefundRequestNo
     *
     * @return string
     */
    public function getMerchantRefundRequestNo()
    {
        return $this->container['merchantRefundRequestNo'];
    }

    /**
     * Sets merchantRefundRequestNo
     *
     * @param string $merchantRefundRequestNo <p>业务商户退款订单号</p>
     *
     * @return $this
     */
    public function setMerchantRefundRequestNo($merchantRefundRequestNo)
    {
        $this->container['merchantRefundRequestNo'] = $merchantRefundRequestNo;

        return $this;
    }

    /**
     * Gets purchasePlatformId
     *
     * @return string
     */
    public function getPurchasePlatformId()
    {
        return $this->container['purchasePlatformId'];
    }

    /**
     * Sets purchasePlatformId
     *
     * @param string $purchasePlatformId <pre>采购方在供应方的平台id</pre>
     *
     * @return $this
     */
    public function setPurchasePlatformId($purchasePlatformId)
    {
        $this->container['purchasePlatformId'] = $purchasePlatformId;

        return $this;
    }

    /**
     * Gets systemOrderNo
     *
     * @return string
     */
    public function getSystemOrderNo()
    {
        return $this->container['systemOrderNo'];
    }

    /**
     * Sets systemOrderNo
     *
     * @param string $systemOrderNo <p>易宝系统唯一订单号</p>
     *
     * @return $this
     */
    public function setSystemOrderNo($systemOrderNo)
    {
        $this->container['systemOrderNo'] = $systemOrderNo;

        return $this;
    }

    /**
     * Gets refundAmount
     *
     * @return float
     */
    public function getRefundAmount()
    {
        return $this->container['refundAmount'];
    }

    /**
     * Sets refundAmount
     *
     * @param float $refundAmount <p>退款金额</p>
     *
     * @return $this
     */
    public function setRefundAmount($refundAmount)
    {
        $this->container['refundAmount'] = $refundAmount;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status <p>退款状态</p> <pre>0：处理中</pre> <pre>1：退款成功</pre> <pre>2：退款失败</pre>
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets refundSuccessTime
     *
     * @return string
     */
    public function getRefundSuccessTime()
    {
        return $this->container['refundSuccessTime'];
    }

    /**
     * Sets refundSuccessTime
     *
     * @param string $refundSuccessTime <p>退款成功时间</p>
     *
     * @return $this
     */
    public function setRefundSuccessTime($refundSuccessTime)
    {
        $this->container['refundSuccessTime'] = $refundSuccessTime;

        return $this;
    }

    /**
     * Gets trxType
     *
     * @return string
     */
    public function getTrxType()
    {
        return $this->container['trxType'];
    }

    /**
     * Sets trxType
     *
     * @param string $trxType <p>在字段用来表示通知类型是交易还是退款。<br />只有在异步通知结果里该参数才有值</p>
     *
     * @return $this
     */
    public function setTrxType($trxType)
    {
        $this->container['trxType'] = $trxType;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


